package main

const dummyTaskResponse = `{
  "tags": [
    [
      "JobType",
      "experience"
    ],
    [
      "ProjectID",
      "e5b316a8-7e02-40a4-9af2-0cff91213ec9"
    ],
    [
      "OrgID",
      "e2e.resim.ai"
    ]
  ],
  "taskName": "f6b585cb-24f7-4b5c-be8e-76347b94bd09-experience",
  "containerTimeout": "1h",
  "workerEnvironmentVariables": [
    [
      "RERUN_WORKER_WORKER_API_URL",
      "https://workerapi.resim.io/worker/v1/"
    ],
    [
      "RERUN_WORKER_ENVIRONMENT_TYPE",
      "external"
    ],
    [
      "RERUN_WORKER_PROJECT_ID",
      "e5b316a8-7e02-40a4-9af2-0cff91213ec9"
    ],
    [
      "RERUN_WORKER_BATCH_ID",
      "d33e7141-8f88-43be-a65f-eca73c0b3a61"
    ],
    [
      "RERUN_WORKER_GPU_COUNT",
      "0"
    ],
    [
      "RERUN_WORKER_S3_ROLE_ARN",
      ""
    ],
    [
      "RERUN_WORKER_AUTH_TOKEN",
      "{\"access_token\":\"dummy-value\",\"token_type\":\"Bearer\",\"expiry\":\"2024-11-09T11:56:54.228999515Z\"}"
    ],
    [
      "RERUN_WORKER_JOB_ID",
      "f6b585cb-24f7-4b5c-be8e-76347b94bd09"
    ],
    [
      "RERUN_WORKER_JOB_MEMORY",
      "16384"
    ],
    [
      "RERUN_WORKER_API_URL",
      "https://workerapi.resim.io/v1/"
    ],
    [
      "RERUN_WORKER_ENVIRONMENT",
      "staging"
    ],
    [
      "RERUN_WORKER_S3_ROLE_EXTERNAL_ID",
      ""
    ],
    [
      "RERUN_WORKER_CUSTOMER_CONTAINER_ROLE_ARN",
      ""
    ],
    [
      "RERUN_WORKER_JOB_TYPE",
      "experience"
    ],
    [
      "RERUN_WORKER_SHARED_MEMORY_MB",
      "64"
    ],
    [
      "RERUN_WORKER_BUILD_IMAGE_URI",
      "public.ecr.aws/docker/library/hello-world:latest"
    ],
    [
      "RERUN_WORKER_EXPERIENCE_LOCATION",
      "/tmp/test-input"
    ],
    [
      "RERUN_WORKER_PARAMETERS",
      "{}"
    ],
    [
      "RERUN_WORKER_TEST_CONFIG",
      "{\"experienceID\":\"cbf186d3-8079-4a20-99e4-e61aea91b5f4\",\"experienceName\":\"foobar\",\"experienceLocation\":\"/tmp/test-input\",\"branchName\":\"main\",\"buildVersion\":\"0.0.1\",\"buildID\":\"be428cd3-d00e-46bf-98a2-ab7d4971b8c4\",\"systemName\":\"foobar\",\"systemID\":\"6e70cee4-25e1-4a6e-952b-cb8acdae5a9c\",\"environmentType\":\"external\"}"
    ],
    [
      "RERUN_WORKER_JOB_CPU",
      "4"
    ],
    [
      "RERUN_WORKER_DEFAULT_REGION",
      "us-east-1"
    ],
    [
      "RERUN_WORKER_ORG_ID",
      "e2e.resim.ai"
    ],
    [
      "RERUN_WORKER_TASK_ID",
      "8acf2aa5-2259-401b-965a-c8ffec9883bc"
    ]
  ],
  "workerImageURI": "public.ecr.aws/resim/experience-worker:ef41d3b7a46a502fef074eb1fd0a1aff54f7a538"
}`
