# Dockerfile to create a customer image with local experience data
# trunk-ignore(hadolint/DL3007)
FROM 909785973729.dkr.ecr.us-east-1.amazonaws.com/rerun-end-to-end-test-experience-build:latest

COPY ./test_experience_data/ /
