// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// AgentCheckinInput defines model for agentCheckinInput.
type AgentCheckinInput struct {
	AgentID      *string `json:"agentID,omitempty"`
	AgentVersion *string `json:"agentVersion,omitempty"`

	// Paused Self-reported quiesced acknowledgement. A pause-aware agent sets
	// this to true only once it has observed the pause and its in-flight
	// worker has exited (it is in the paused sleep loop). It is
	// level-triggered — sent on every checkin while quiesced — and the
	// server records it only while the agent is actually paused, so a
	// stale ack racing an unpause is ignored. Optional: absent means the
	// agent has not acknowledged quiescing.
	Paused     *bool        `json:"paused,omitempty"`
	PoolLabels *[]PoolLabel `json:"poolLabels,omitempty"`
}

// AgentCheckinOutput defines model for agentCheckinOutput.
type AgentCheckinOutput struct {
	AuthToken *string `json:"authToken,omitempty"`

	// PauseReason The reason recorded with the pause, for the host operator's logs. Present only when paused and a reason was given.
	PauseReason *string `json:"pauseReason,omitempty"`

	// Paused True when the agent is paused and must not launch workers: it
	// should log the pause, skip launching, and keep checking in on its
	// existing cadence until this clears. A paused checkin is still a
	// successful checkin and must not count toward the agent's max-error
	// process exit. Optional — absent or false means run normally, so an
	// older agent binary talking to this API (or a newer agent talking
	// to an older API) safely defaults to running.
	Paused *bool `json:"paused,omitempty"`

	// PausedAt When the pause was set. Present only when paused.
	PausedAt *time.Time `json:"pausedAt,omitempty"`

	// PausedBy Who set the pause (email, or client identity for machine tokens). Present only when paused.
	PausedBy                   *string                `json:"pausedBy,omitempty"`
	RequiredAgentVersion       *string                `json:"requiredAgentVersion,omitempty"`
	WorkerEnvironmentVariables *[]EnvironmentVariable `json:"workerEnvironmentVariables,omitempty"`
	WorkerImageURI             *string                `json:"workerImageURI,omitempty"`
}

// EnvironmentVariable defines model for environmentVariable.
type EnvironmentVariable = []string

// PoolLabel defines model for poolLabel.
type PoolLabel = string

// AgentCheckinJSONRequestBody defines body for AgentCheckin for application/json ContentType.
type AgentCheckinJSONRequestBody = AgentCheckinInput

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// AgentCheckinWithBody performs a POST /agent/checkin (the `AgentCheckin` operationId) request,
	// with any type of body and a specified content type.
	//
	// Startup endpoint for agents.
	AgentCheckinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AgentCheckin performs a POST /agent/checkin (the `AgentCheckin` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Startup endpoint for agents.
	AgentCheckin(ctx context.Context, body AgentCheckinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AgentAPIPing performs a GET /agentapiping (the `AgentAPIPing` operationId) request.
	//
	// Used for testing, to validate the specific existence of the Agent API
	AgentAPIPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Health performs a GET /health (the `Health` operationId) request.
	//
	// Returns whether the service is healthy or not.
	Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// AgentCheckinWithBody performs a POST /agent/checkin (the `AgentCheckin` operationId) request,
// with any type of body and a specified content type.
//
// Startup endpoint for agents.
func (c *Client) AgentCheckinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAgentCheckinRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AgentCheckin performs a POST /agent/checkin (the `AgentCheckin` operationId) request.
// Takes a body of the `application/json` content type.
//
// Startup endpoint for agents.
func (c *Client) AgentCheckin(ctx context.Context, body AgentCheckinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAgentCheckinRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AgentAPIPing performs a GET /agentapiping (the `AgentAPIPing` operationId) request.
//
// Used for testing, to validate the specific existence of the Agent API
func (c *Client) AgentAPIPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAgentAPIPingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Health performs a GET /health (the `Health` operationId) request.
//
// Returns whether the service is healthy or not.
func (c *Client) Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAgentCheckinRequest calls the generic AgentCheckin builder with application/json body
func NewAgentCheckinRequest(server string, body AgentCheckinJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAgentCheckinRequestWithBody(server, "application/json", bodyReader)
}

// NewAgentCheckinRequestWithBody constructs an http.Request for the AgentCheckin method, with any body, and a specified content type
func NewAgentCheckinRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agent/checkin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAgentAPIPingRequest constructs an http.Request for the AgentAPIPing method
func NewAgentAPIPingRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agentapiping")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthRequest constructs an http.Request for the Health method
func NewHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// AgentCheckinWithBodyWithResponse performs a POST /agent/checkin (the `AgentCheckin` operationId) request,
	// with any type of body and a specified content type.
	//
	// Startup endpoint for agents.
	//
	// Returns a wrapper object for the known response body format(s).
	AgentCheckinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AgentCheckinResponse, error)

	// AgentCheckinWithResponse performs a POST /agent/checkin (the `AgentCheckin` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Startup endpoint for agents.
	AgentCheckinWithResponse(ctx context.Context, body AgentCheckinJSONRequestBody, reqEditors ...RequestEditorFn) (*AgentCheckinResponse, error)

	// AgentAPIPingWithResponse performs a GET /agentapiping (the `AgentAPIPing` operationId) request.
	//
	// Used for testing, to validate the specific existence of the Agent API
	//
	// Returns a wrapper object for the known response body format(s).
	AgentAPIPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AgentAPIPingResponse, error)

	// HealthWithResponse performs a GET /health (the `Health` operationId) request.
	//
	// Returns whether the service is healthy or not.
	//
	// Returns a wrapper object for the known response body format(s).
	HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error)
}

type AgentCheckinResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AgentCheckinOutput
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AgentCheckinResponse) GetJSON200() *AgentCheckinOutput {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r AgentCheckinResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AgentCheckinResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AgentCheckinResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AgentCheckinResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AgentAPIPingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r AgentAPIPingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AgentAPIPingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AgentAPIPingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AgentAPIPingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r HealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AgentCheckinWithBodyWithResponse performs a POST /agent/checkin (the `AgentCheckin` operationId) request,
// with any type of body and a specified content type.
//
// Startup endpoint for agents.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AgentCheckinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AgentCheckinResponse, error) {
	rsp, err := c.AgentCheckinWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAgentCheckinResponse(rsp)
}

// AgentCheckinWithResponse performs a POST /agent/checkin (the `AgentCheckin` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Startup endpoint for agents.
func (c *ClientWithResponses) AgentCheckinWithResponse(ctx context.Context, body AgentCheckinJSONRequestBody, reqEditors ...RequestEditorFn) (*AgentCheckinResponse, error) {
	rsp, err := c.AgentCheckin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAgentCheckinResponse(rsp)
}

// AgentAPIPingWithResponse performs a GET /agentapiping (the `AgentAPIPing` operationId) request.
//
// # Used for testing, to validate the specific existence of the Agent API
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AgentAPIPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AgentAPIPingResponse, error) {
	rsp, err := c.AgentAPIPing(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAgentAPIPingResponse(rsp)
}

// HealthWithResponse performs a GET /health (the `Health` operationId) request.
//
// Returns whether the service is healthy or not.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error) {
	rsp, err := c.Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthResponse(rsp)
}

// ParseAgentCheckinResponse parses an HTTP response from a AgentCheckinWithResponse call
func ParseAgentCheckinResponse(rsp *http.Response) (*AgentCheckinResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AgentCheckinResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AgentCheckinOutput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	}

	return response, nil
}

// ParseAgentAPIPingResponse parses an HTTP response from a AgentAPIPingWithResponse call
func ParseAgentAPIPingResponse(rsp *http.Response) (*AgentAPIPingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AgentAPIPingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHealthResponse parses an HTTP response from a HealthWithResponse call
func ParseHealthResponse(rsp *http.Response) (*HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
