---
name: Security and SBOM
on:
  workflow_call:
    inputs:
      severity:
        required: false
        type: string
        default: HIGH,CRITICAL
      repository:
        required: true
        type: string
    secrets:
      app-id:
        required: true
      private-key:
        required: true
      github-token:
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: sec
  cancel-in-progress: true

jobs:
  sbom:
    name: Scan
    runs-on: ubuntu-24.04
    outputs:
      message: ${{ steps.scan-message.outputs.message }}
      body: ${{ steps.scan-output.outputs.body }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deployment_bot_comment:
    name: Deployment Bot Comment
    if: github.event_name == 'pull_request'
    needs: [sbom]
    uses: ./.github/workflows/create-update-deployment-bot-comment.yml
    with:
      repository: ${{ inputs.repository }}
      pr_number: ${{ github.event.pull_request.number }}
      ref_name: ${{ github.ref_name }}
      comment_key: sec-
      comment_body: |
        # :lock: Vulnerability Scan Summary

        ${{ needs.sbom.outputs.message }}

        See [Handling Vulnerabilities](https://github.com/resim-ai/rerun/blob/main/docs/handling-vulnerabilities.md) for instructions on what to do with this information.

        <details><summary>Show Details</summary>

        \`\`\`\n
        ${{ needs.sbom.outputs.body }}
        \`\`\`

        </details>

    secrets:
      DEPLOYMENT_BOT_APP_ID: ${{ secrets.app-id }}
      DEPLOYMENT_BOT_PRIVATE_KEY: ${{ secrets.private-key }}

# NOTE: Not available on our pricing tier
# - name: Upload Trivy scan results to GitHub Security tab
#   uses: github/codeql-action/upload-sarif@v2
#   with:
#     sarif_file: trivy-results.sarif
