---
name: Go build, unit tests, and Codecov
on:  #trunk-ignore(yamllint/truthy)
  workflow_call:
    inputs:
      GO_VERSION:
        required: true
        type: string
    secrets:
      codecov-token:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Unit tests and Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
          cache: true

      - name: Go Build Cache
        id: go-build-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-cache-

      - name: Install dependencies
        run: go get .

      - name: Extract binary version from ref
        run: |
          if [[ "${{ github.ref_name }}" == main ]]; then
            echo "VERSION=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          else
            REF=$(echo "${{ github.ref_name }}" | cut -d'/' -f1)
            echo "VERSION=pr-$REF" >> "$GITHUB_OUTPUT"
          fi
        id: extract_pr

      - name: Build Go
        if: steps.go-build-cache.outputs.cache-hit != 'true'
        run: go build -o ./agent-linux-amd64-${{ steps.extract_pr.outputs.VERSION }} -buildvcs=false ./cmd
        env:
          VERSION: ${{ steps.extract_pr.outputs.VERSION }}

      - name: Configure AWS Credentials us-east-1
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::909785973729:role/actions-agent
          aws-region: us-east-1

      - name: Upload binary to S3
        if: steps.go-build-cache.outputs.cache-hit != 'true'
        run: aws s3 cp ./agent-* s3://resim-binaries/agent/

      - name: Test and Run coverage
        run: go test . -v -json -race -coverprofile=coverage.out > raw_test_output.json

      - name: Display test output
        if: always()
        run: cat raw_test_output.json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: raw_test_output.json

      # Skip Codecov upload if [skip-codecov] is present in the commit message
      # Only use this when coverage failures are unrelated to the PR's primary purpose
      # (e.g., adding a new lint check causes the patch coverage check to fail)
      - name: Check for Codecov skip
        id: check_skip
        run: |
          if git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }} | grep -qF "[skip-codecov]"; then
            echo "skip_codecov=true" >> "$GITHUB_OUTPUT"
            echo "[skip-codecov] tag found. Codecov upload will be skipped."
          else
            echo "skip_codecov=false" >> "$GITHUB_OUTPUT"
            echo "[skip-codecov] tag not found. Proceeding with Codecov upload."
          fi

      - name: Upload coverage to Codecov
        if: steps.check_skip.outputs.skip_codecov != 'true'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov-token }}
          fail_ci_if_error: true
